### ISSUE TITLE
build errors, failed to cabal install llvm-sclicing

### ISSUE THREAD

**Issue by 14m3** [zhangyz/llvm-slicing#5]
Hello, when I do cabal install in /src directory, I got the errors as following, Could you help me ? Thank you.

Ubuntu 14.04
LLVM 3.4
cabal-install version 1.20.0.3
The Glorious Glasgow Haskell Compilation System, version 7.8.4

>  [ 3 of 22] Compiling LLVM.Analysis.CFG.Internal ( src/LLVM/Analysis/CFG/Internal.hs, dist/build/LLVM/Analysis/CFG/Internal.o )
> 
> src/LLVM/Analysis/CFG/Internal.hs:245:37:
>     Couldn't match type ‘GV.Number’ with ‘GV.GraphID’
>     Expected type: Int -> GV.GraphID
>       Actual type: Int -> GV.Number
>     In the first argument of ‘(.)’, namely ‘GV.Int’
>     In the ‘GV.clusterID’ field of a record
> Failed to install llvm-analysis-0.3.0
> cabal: Error: some packages failed to install:
> hashtables-1.2.3.0 failed during the building phase. The exception was:
> ExitFailure 1
> llvm-analysis-0.3.0 failed during the building phase. The exception was:
> ExitFailure 1
> llvm-data-interop-0.3.0 depends on hashtables-1.2.3.0 which failed to install.
> llvm-slicing-0.3.3 depends on llvm-analysis-0.3.0 which failed to install.

**Comment by zhangyz** [comment]
It is because that the version of Haskell library hashtable installed in your computer does not meet (e.g. higher) the requirement for Haskell libray llvm-analysis. There are two solutions: 1) uninstall your higher version of hashtable , reinstall its lower one such as 1.1.2.0, and try them again; or 2) directly download our pre-built binary in the folder bin/. In addition, for more detailed install information about llvm-analysis, please see its website: http://hackage.haskell.org/package/llvm-analysis. I strongly recommend you to select Solution 2. Thanks for your interest in our llvm-slicing.

**Comment by 14m3** [comment]
@zhangyz Thanks, but I have to use LLVM3.4 on Ubuntu14.04. I' ll try solution1 to see if I can solve it
