### ISSUE TITLE
How can i use llvm-slicing to split the project which includes multiple source files

### ISSUE THREAD

**Issue by PegX** [zhangyz/llvm-slicing#7]
Hi,  I wanna ask how can i use your framework to split a project which has multiple source files. 
For example, under the directory of source, there are several programs. Just take barcode for example, there are 6 directories and 221 files. Although not all of them can be sliced with llvm-slicing, there are also mutliple c implementation should be splitted. 
I want to know is it possilbe to use llvm-slicing directly for this barcode program. Or should I write a small script which utilizes `llvm-slicing $name` repeatedly?

**Comment by zhangyz** [comment]
Sorry, `llvm-slicing` now is not used directly for a barcode project with multiple source files, since it is just an IR slicer. Therefore, for a multi-programs project, you can first compile these programs into corresponding IRs, then combine them into a single IR with the LLVM tool `llvm-link`, and finally use `llvm-slicing` to slice this project.
